[project]
name = "logosdelivery"
version = "0.0.1"
authors = [
  { name="Waku Dev Team", email="ivansete@status.im" },
]
description = "Python bindings for liblogosdelivery"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["cffi>=1.16.0", "cbor2>=6.1.4", "result>=0.17.0"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["logosdelivery"]
